name: Deploy to Environment
on:
 push
permissions:
  id-token: write
  contents: read

jobs:
  C4_Build:
    runs-on: 
      ubuntu-latest
    steps:
      - name: c4 clone
        uses: actions/checkout@v3
        with:
          repository: exasol/ccc
          ref: master
          token: ${{secrets.CCC_GITHUB_TOKEN}}
          path: c4
      #- name: c4 build
        #working-directory: c4
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: setup go
        #uses: actions/setup-go@v3
        #with:
          #go-version-file: 1.18.1
        #run: |
          #config/ccc make