name: Deploy to Environment
on:
 push:
  tags:
    - '*'
permissions:
  id-token: write
  contents: read

jobs:
  Deploy to Development:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      TAG: ${{github}}
    steps:
    - name: Dev Environment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::533884745449:role/github-actions-session-role
        role-session-name: github-actions-session-role
        aws-region: ${{env.AWS_DEFAULT_REGION}}
    - name: ${{github.ref}}
      run: |
        echo ${{ env.AWS_DEFAULT_REGION }}