name: Deploy to Environment
on:
  push:
    tags: 
      - '*'
permissions:
  id-token: write
  contents: read

jobs:
  c4build:
    runs-on: 
      ubuntu-latest
    steps:
      - name: c4 clone
        uses: actions/checkout@v3
        with:
          repository: exasol/ccc
          ref: master
          token: ${{secrets.CCC_GITHUB_TOKEN}}
          path: c4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:  
          go-version: '1.18.1'
          check-latest: true
      #- name: c4 build
        #run: |
          #cd ${{github.workspace}}/c4/
          #config/ccc make
      - name: get build ui path
      -  uses: actions/checkout@v3
         id: tagname
         run: |
           git tag | sort -V | tail -n 1
      - run: echo tag version is ${{steps.tagname.outputs.stdout}}
      #- name: Upload the Fetch
        #uses: actions/upload-artifact@v3
        #with:
          #name: ui
          #path: ~/.ccc/x/u/branchr/


          


