name: Deploy to Environment
on:
 push
permissions:
  id-token: write
  contents: read

jobs:
  C4_Build:
    runs-on: 
      ubuntu-latest
    steps:
      - name: c4 clone
        uses: actions/checkout@v3
        with:
          repository: exasol/ccc
          ref: master
          token: ${{secrets.CCC_GITHUB_TOKEN}}
          path: c4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
          check-latest: true
      - name: c4 build
        run: |
          cd ${{github.workspace}}/c4/
          config/ccc make
      - name: ui fetch
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          CCC_AWS_REGION=eu-west-1 ${{github.workspace}}/c4/bin/c4 fetch @ui-1.180.0
          BUILD_PATH=$(${{github.workspace}}/c4/bin/c4 info @ui-1.180.0 Local-Linkdir)
          ls -lrt ~/.ccc$BUILD_PATH/dist/apps/maintenance
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        with:
          repository: MajorScruffy/delete-old-workflow-runs   # replace this with your own repository
          older-than-seconds: 540                           # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
