name: Deploy to Environment
on:
 push
permissions:
  id-token: write
  contents: read

jobs:
  C4_Build:
    runs-on: 
      ubuntu-latest
    steps:
      - name: c4 clone
        uses: actions/checkout@v3
        with:
          repository: exasol/ccc
          ref: master
          token: ${{secrets.CCC_GITHUB_TOKEN}}
          path: c4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
          check-latest: true
      - name: c4 build
        run: |
          cd ${{github.workspace}}/c4/
          config/ccc make
          CCC_AWS_REGION=eu-west-1 bin/c4 fetch @ui-1.174.0