name: Deploy to Environment
on:
 push:
  tags:
    - '*'
permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
    steps:
    - name: Dev Environment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::533884745449:role/github-actions-session-role
        role-session-name: github-actions-session-role
        aws-region: ${{env.AWS_DEFAULT_REGION}}
    - name: Create bucket
      run: |
        aws s3 mb s3://oooflakron-odjali-ri2 --region ${{env.AWS_DEFAULT_REGION}}