name: Deploy to Environment
on:
 push
permissions:
  id-token: write
  contents: read

jobs:
  C4_Build:
    runs-on: 
      ubuntu-latest
    steps:
      - name: c4 clone
        uses: actions/checkout@v3
        with:
          repository: exasol/ccc
          ref: master
          token: ${{secrets.CCC_GITHUB_TOKEN}}
          path: c4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
          check-latest: true
      - name: c4 build
        run: |
          sudo apt install build-essential -y
          sudo apt-get install manpages-dev -y
          sudo apt install gcc -y
          sudo apt-get update -y && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y sudo lsb-release jq awscli curl
          ${{github.workspace}}/c4/config/ccc make