name: Deploy to Environment
on:
 push:
  tags:
    - '*'
permissions:
  id-token: write
  contents: read

jobs:
  Deploy2Development:
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF#refs/heads/}
      AWS_DEFAULT_REGION: 'us-east-1'
    steps:
    - name: Dev Environment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::533884745449:role/github-actions-session-role
        role-session-name: github-actions-session-role
        aws-region: ${{env.AWS_DEFAULT_REGION}}
    - name: ${{env.TAG}}
      run: |
        echo "Welcome to the Dev environment"